wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.11.7
    cli_version: 0.16.1
    framework: sklearn
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1702057306.010287
    t:
      1:
      - 5
      - 53
      - 55
      2:
      - 5
      - 53
      - 55
      3:
      - 16
      - 23
      4: 3.11.7
      5: 0.16.1
      8:
      - 1
      - 3
      - 5
      13: windows-amd64
test_size:
  desc: null
  value: 0.3
train_len:
  desc: null
  value: 968
test_len:
  desc: null
  value: 415
