wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.11.7
    cli_version: 0.16.1
    framework: sklearn
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1702058425.560191
    t:
      1:
      - 5
      - 53
      - 55
      2:
      - 5
      - 53
      - 55
      3:
      - 2
      - 16
      - 23
      4: 3.11.7
      5: 0.16.1
      8:
      - 1
      - 3
      - 5
      10:
      - 5
      13: windows-amd64
    viz:
      class_proportions:
        id: wandb/class_proportions/v1
        historyFieldSettings:
          x-axis: _step
          key: class_proportions
      learning_curve:
        id: wandb/learning_curve/v1
        historyFieldSettings:
          x-axis: _step
          key: learning_curve
      roc:
        id: wandb/roc/v1
        historyFieldSettings:
          x-axis: _step
          key: roc
      precision_recall:
        id: wandb/pr_curve/v1
        historyFieldSettings:
          x-axis: _step
          key: precision_recall
test_size:
  desc: null
  value: 0.3
train_len:
  desc: null
  value: 968
test_len:
  desc: null
  value: 415
